name: CI/CD

on:
  push:
    branches:
      - '*'
      - '!main'
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pylint black pytest pytest-cov
      
      - name: Run pylint and black
        run: |
          pylint your_module_or_package
          black --check your_module_or_package
      
      - name: Run tests with coverage
        run: |
          pytest --cov=your_module_or_package
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      
      - name: Upload coverage report
        uses: codecov/codecov-action@v2

  deploy-to-aws-ecr:
    needs: lint-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Authenticate with AWS ECR
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: your_aws_region
      
      # Build and push Docker image to AWS ECR
      - name: Build and push Docker image
        run: |
          docker build -t your_docker_image_tag .
          docker tag hackaton 204792748194.dkr.ecr.your_aws_region.amazonaws.com/hackaton:latest
          docker push 204792748194.dkr.ecr.your_aws_region.amazonaws.com/hackaton:latest
